### ISSUE TITLE
pydicom import error

### ISSUE THREAD

**Issue by tcdewit** [MedPhysQC/CR_Flatfield#1]
Just got the following error message when executing the module (Ubuntu 18.04.2 LTS):   

```
Error during execution of process
Exception:
Traceback (most recent call last):
  File "/home/wadqc/WADROOT/WAD_QC/Modules/mod2d_jch7z/Bucky_Flatfield.py", line 43, in <module>
    import dicom
  File "/home/wadqc/Envs/wad2env3/lib/python3.6/site-packages/dicom.py", line 11, in <module>
    raise ImportError(msg)
ImportError: 
Pydicom via 'import dicom' has been removed in pydicom version 1.0.
Please install the `dicom` package to restore function of code relying
on pydicom 0.9.9 or earlier. E.g. `pip install dicom`.
Alternatively, most code can easily be converted to pydicom > 1.0 by
changing import lines from 'import dicom' to 'import pydicom'.
See the Transition Guide at
https://pydicom.github.io/pydicom/stable/transition_to_pydicom1.html.
```

**Comment by tcdewit** [comment]
Just figured out the bugfix was already made but wasn't published as a new release.
